[package]
name = "fossil"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
glob = "0.3"
chrono = { version = "0.4", features = ["serde"] }
tui = "0.19"
crossterm = "0.27"

