[package]
name = "fossil"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "fossil"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
toml = "0.8"
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2.0.18"
axum = { version = "0.8", default-features = false, features = ["http1", "query", "json", "tokio"] }
tokio = { version = "1", features = ["rt-multi-thread", "net", "fs", "sync"] }
serde_urlencoded = "0.7"
tower-http = { version = "0.6", features = ["fs"] }
maud = { version = "0.27", features = ["axum"] }
