name = "octane"
description = "Octane 2.0 steady-state JS throughput"
default_iterations = 5
binary = "../../firefox/jsshell"
cwd = "../../firefox/js/src/octane"

[configs.AOT]
command = "taskset -c 2 ../../../../jsshell --aot-bl -f run.js"

[configs.JIT]
command = "taskset -c 2 ../../../../jsshell -f run.js"
